/*
 * Copyright (c) 2024 IED
 *
 */

#ifndef DIGI_PROFILE_H_
#define DIGI_PROFILE_H_

#define DIGI_PROFILE_ID 0xC105

#define DIGI_BINARY_VALUE_CLUSTER 0x0011
#define DIGI_BINARY_VALUE_SOURCE_ENDPOINT 232
#define DIGI_BINARY_VALUE_DESTINATION_ENDPOINT 232

#define DIGI_COMMISSIONING_CLUSTER 0x0015
#define DIGI_COMMISSIONING_REPLY_CLUSTER 0x0095
#define DIGI_COMMISSIONING_SOURCE_ENDPOINT 230
#define DIGI_COMMISSIONING_DESTINATION_ENDPOINT 230

#define PRODUCT_TYPE     0x00000001 // I will assign that value as product type of the Fanstel BT840E
#define MANUFACTURED_ID  0x0001     // I will assign that value as manufactured ID of the Fanstel BT840E

#endif /* DIGI_PROFILE_H_ */

