/*
 * Copyright (c) 2024 IED
 *
 */

#ifndef DIGI_PROFILE_H_
#define DIGI_PROFILE_H_

#define DIGI_PROFILE_ID 0xC105

#define DIGI_BINARY_VALUE_CLUSTER 0x0011
#define DIGI_BINARY_VALUE_SOURCE_ENDPOINT 232
#define DIGI_BINARY_VALUE_DESTINATION_ENDPOINT 232

#define DIGI_COMMISSIONING_CLUSTER 0x0015
#define DIGI_COMMISSIONING_REPLY_CLUSTER 0x0095
#define DIGI_COMMISSIONING_SOURCE_ENDPOINT 230
#define DIGI_COMMISSIONING_DESTINATION_ENDPOINT 230

#define DIGI_AT_COMMAND_CLUSTER 0x0021
#define DIGI_AT_COMMAND_REPLY_CLUSTER 0x00A1
#define DIGI_AT_COMMAND_SOURCE_ENDPOINT 230
#define DIGI_AT_COMMAND_DESTINATION_ENDPOINT 230

#define DIGI_AT_PING_CLUSTER 0x0012
#define DIGI_AT_PING_SOURCE_ENDPOINT 219
#define DIGI_AT_PING_DESTINATION_ENDPOINT 232

#define DIGI_AT_PONG_CLUSTER 0x0011
#define DIGI_AT_PONG_SOURCE_ENDPOINT 232
#define DIGI_AT_PONG_DESTINATION_ENDPOINT 219

#define DIGI_FOTA_CLUSTER 0x0019


#define PRODUCT_TYPE     0x00000001 // I will assign that value as product type of the Fanstel BT840E
#define MANUFACTURED_ID  0x0001     // I will assign that value as manufactured ID of the Fanstel BT840E


#endif /* DIGI_PROFILE_H_ */

