/*
 * Copyright (c) 2024 IED
 *
 */

#ifndef ZIGBEE_DEVICE_PROFILE_H_
#define ZIGBEE_DEVICE_PROFILE_H_

#define ZIGBEE_DEVICE_PROFILE_ID 0x0000
#define IEEE_ADDRESS_REQUEST_CLUSTER 0x0001
#define IEEE_ADDRESS_RESPONSE_CLUSTER 0x8001
#define ZIGBEE_DEVICE_OBJECT_SOURCE_ENDPOINT 0x00
#define ZIGBEE_DEVICE_OBJECT_DESTINATION_ENDPOINT 0x00

#define IEEE_ADDRESS_REQUEST_TYPE 0x00
#define SINGLE_REPLY_START_INDEX 0x00

#endif /* ZIGBEE_DEVICE_PROFILE_H_ */

